services:
  postgres:
    image: postgres:16
    container_name: obe-postgres-backend
    environment:
      POSTGRES_DB: obe
      POSTGRES_USER: obe
      POSTGRES_PASSWORD: obe
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: obe-redis
    ports:
      - "6379:6379"

volumes:
  pgdata: